apiVersion: batch/v1
kind: CronJob
metadata:
  name: ecr-credentials-refresh
  namespace: image-uploader
spec:
  schedule: "0 */6 * * *"  # Every 6 hours
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: ecr-refresh-sa
          restartPolicy: OnFailure
          containers:
          - name: ecr-refresh
            image: amazon/aws-cli:latest
            command:
            - /bin/sh
            - -c
            - |
              # Get ECR token
              TOKEN=$(aws ecr get-login-password --region us-east-1)
              
              # Update the Kubernetes secret
              kubectl delete secret ecr-credentials -n image-uploader --ignore-not-found=true
              kubectl create secret docker-registry ecr-credentials \
                --docker-server=503015902469.dkr.ecr.us-east-1.amazonaws.com \
                --docker-username=AWS \
                --docker-password="$TOKEN" \
                -n image-uploader
              
              echo "ECR credentials refreshed successfully"
            env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_DEFAULT_REGION
              value: "us-east-1"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecr-refresh-sa
  namespace: image-uploader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ecr-refresh-role
  namespace: image-uploader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ecr-refresh-binding
  namespace: image-uploader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ecr-refresh-role
subjects:
- kind: ServiceAccount
  name: ecr-refresh-sa
  namespace: image-uploader
