apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-uploader-pvc
  namespace: image-uploader
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-uploader-metadata-pvc
  namespace: image-uploader
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 1Gi