apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-uploader-pvc
  namespace: image-uploader
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2